# Generated by Django 4.1.4 on 2022-12-27 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docker_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='item',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price_dena',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='count_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_name_3', related_query_name='item_name_3', to='docker_admin.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_name_2', related_query_name='item_name_2', to='docker_admin.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='total_price_is_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='balans_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balans_1', related_query_name='balans_1', to='docker_admin.balans'),
        ),
        migrations.AddField(
            model_name='trade',
            name='balans_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balans_2', related_query_name='balans_2', to='docker_admin.balans'),
        ),
        migrations.AddField(
            model_name='trade',
            name='ostatok_balanc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='ostatok_balanc_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='price_total_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='balans',
            name='balans',
            field=models.DecimalField(blank=True, decimal_places=2, default=400, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_admin.codename'),
        ),
        migrations.AlterField(
            model_name='item',
            name='valuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docker_admin.currency'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
