# Generated by Django 4.1.4 on 2022-12-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codename',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='codename',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
