# Generated by Django 4.1.4 on 2022-12-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0003_remove_codename_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuta', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
