# Generated by Django 4.1.4 on 2023-02-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0003_remove_user_verification_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
