# Generated by Django 4.1.4 on 2022-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0003_alter_offer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='balans_1',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='balans_2',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='ostatok_balanc',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='ostatok_balanc_1',
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity_client',
            field=models.DecimalField(blank=True, decimal_places=2, default=400, max_digits=5, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity_seller',
            field=models.DecimalField(blank=True, decimal_places=2, default=400, max_digits=5, max_length=5, null=True),
        ),
    ]
