# Generated by Django 4.1.4 on 2023-02-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0004_offer_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
    ]
