# Generated by Django 4.1.4 on 2022-12-27 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docker_admin', '0004_remove_trade_balans_1_remove_trade_balans_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balans',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
