# Generated by Django 4.1.4 on 2022-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0005_item_offer_price_watchlist_trade_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Ok'), (2, 'Good'), (3, 'Fine'), (4, 'Amazing'), (5, 'Incredible')], null=True),
        ),
    ]
