# Generated by Django 4.1.4 on 2022-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0006_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'BUY'), (2, 'ADD')], null=True),
        ),
    ]
