# Generated by Django 4.1.4 on 2022-12-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0007_alter_offer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='type',
            new_name='type_function',
        ),
    ]
