# Generated by Django 4.1.4 on 2022-12-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_admin', '0008_balans_rename_type_offer_type_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceprice', related_query_name='priceprice', to='docker_admin.price'),
        ),
    ]
