# Generated by Django 4.1.4 on 2023-01-16 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docker_admin', '0008_offer_is_activate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balans',
            new_name='Balance',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='balans',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='is_publishid',
            new_name='is_published',
        ),
    ]
